/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tableprojectdemmo;

/**
 *
 * @author abdal
 */
public class custom_table extends javax.swing.JFrame {

    /**
     * Creates new form custom_table
     */
    static public String cellText[];

    public custom_table(String celltext[]) {
        initComponents();
        cellText = celltext;
        TLable1.setText(celltext[0]);
        TLable2.setText(celltext[1]);
        TLable3.setText(celltext[2]);
        TLable4.setText(celltext[2]);
        TLable5.setText(celltext[2]);
        TLable6.setText(celltext[2]);
        TLable7.setText(celltext[2]);
        TLable8.setText(celltext[2]);
        TLable9.setText(celltext[2]);
        TLable10.setText(celltext[2]);
        TLable11.setText(celltext[2]);
        TLable12.setText(celltext[2]);
        TLable13.setText(celltext[2]);
        TLable14.setText(celltext[2]);
        TLable15.setText(celltext[2]);
        TLable16.setText(celltext[2]);
        TLable17.setText(celltext[2]);
        TLable18.setText(celltext[2]);
        TLable19.setText(celltext[2]);
        TLable20.setText(celltext[2]);
        TLable21.setText(celltext[2]);
        TLable22.setText(celltext[2]);
        TLable23.setText(celltext[2]);
        TLable24.setText(celltext[2]);
        TLable25.setText(celltext[2]);
        TLable26.setText(celltext[2]);
        TLable27.setText(celltext[2]);
        TLable28.setText(celltext[2]);
        TLable29.setText(celltext[2]);
        TLable30.setText(celltext[2]);
        TLable31.setText(celltext[2]);
        TLable32.setText(celltext[2]);
        TLable33.setText(celltext[2]);
        TLable34.setText(celltext[2]);
        TLable35.setText(celltext[2]);
        TLable36.setText(celltext[2]);
        TLable37.setText(celltext[2]);
        TLable38.setText(celltext[2]);
        TLable39.setText(celltext[2]);
        TLable40.setText(celltext[2]);
        TLable41.setText(celltext[2]);
        TLable42.setText(celltext[2]);
        TLable43.setText(celltext[2]);
        TLable44.setText(celltext[2]);
        TLable45.setText(celltext[2]);
        TLable46.setText(celltext[2]);
        TLable47.setText(celltext[2]);
        TLable48.setText(celltext[2]);
        TLable49.setText(celltext[2]);
        TLable50.setText(celltext[2]);
        TLable51.setText(celltext[2]);
        TLable52.setText(celltext[2]);
        TLable53.setText(celltext[2]);
        TLable54.setText(celltext[2]);



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        jSeparator22 = new javax.swing.JSeparator();
        jSeparator23 = new javax.swing.JSeparator();
        jSeparator24 = new javax.swing.JSeparator();
        jSeparator25 = new javax.swing.JSeparator();
        jSeparator26 = new javax.swing.JSeparator();
        jSeparator27 = new javax.swing.JSeparator();
        TLable1 = new javax.swing.JLabel();
        TLable2 = new javax.swing.JLabel();
        TLable3 = new javax.swing.JLabel();
        TLable4 = new javax.swing.JLabel();
        TLable5 = new javax.swing.JLabel();
        TLable6 = new javax.swing.JLabel();
        TLable7 = new javax.swing.JLabel();
        TLable8 = new javax.swing.JLabel();
        TLable9 = new javax.swing.JLabel();
        TLable10 = new javax.swing.JLabel();
        TLable11 = new javax.swing.JLabel();
        TLable12 = new javax.swing.JLabel();
        TLable13 = new javax.swing.JLabel();
        TLable14 = new javax.swing.JLabel();
        TLable15 = new javax.swing.JLabel();
        TLable16 = new javax.swing.JLabel();
        TLable17 = new javax.swing.JLabel();
        TLable18 = new javax.swing.JLabel();
        TLable19 = new javax.swing.JLabel();
        TLable20 = new javax.swing.JLabel();
        TLable21 = new javax.swing.JLabel();
        TLable22 = new javax.swing.JLabel();
        TLable23 = new javax.swing.JLabel();
        TLable24 = new javax.swing.JLabel();
        TLable25 = new javax.swing.JLabel();
        TLable26 = new javax.swing.JLabel();
        TLable27 = new javax.swing.JLabel();
        TLable28 = new javax.swing.JLabel();
        TLable29 = new javax.swing.JLabel();
        TLable30 = new javax.swing.JLabel();
        TLable31 = new javax.swing.JLabel();
        TLable32 = new javax.swing.JLabel();
        TLable33 = new javax.swing.JLabel();
        TLable34 = new javax.swing.JLabel();
        TLable35 = new javax.swing.JLabel();
        TLable36 = new javax.swing.JLabel();
        TLable37 = new javax.swing.JLabel();
        TLable38 = new javax.swing.JLabel();
        TLable39 = new javax.swing.JLabel();
        TLable40 = new javax.swing.JLabel();
        TLable41 = new javax.swing.JLabel();
        TLable42 = new javax.swing.JLabel();
        TLable43 = new javax.swing.JLabel();
        TLable44 = new javax.swing.JLabel();
        TLable45 = new javax.swing.JLabel();
        TLable46 = new javax.swing.JLabel();
        TLable47 = new javax.swing.JLabel();
        TLable48 = new javax.swing.JLabel();
        TLable49 = new javax.swing.JLabel();
        TLable50 = new javax.swing.JLabel();
        TLable51 = new javax.swing.JLabel();
        TLable52 = new javax.swing.JLabel();
        TLable53 = new javax.swing.JLabel();
        TLable54 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator13.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel1.setText("Saturday");

        jLabel2.setText("Sunday");

        jLabel3.setText("Monday");

        jLabel4.setText("Tuesday");

        jLabel5.setText("Wednesday");

        jLabel6.setText("Thursday");

        jLabel7.setText("9:00");

        jLabel8.setText("11:00");

        jLabel9.setText("1:00");

        TLable1.setText("Tlable1");

        TLable2.setText("Tlable2");

        TLable3.setText("Tlable3");

        TLable4.setText("Tlable4");

        TLable5.setText("Tlable5");

        TLable6.setText("Tlable6");

        TLable7.setText("Tlable7");

        TLable8.setText("Tlable8");

        TLable9.setText("Tlable9");

        TLable10.setText("Tlable11");

        TLable11.setText("Tlable10");

        TLable12.setText("Tlable12");

        TLable13.setText("Tlable13");

        TLable14.setText("Tlable14");

        TLable15.setText("Tlable15");

        TLable16.setText("Tlable18");

        TLable17.setText("Tlable17");

        TLable18.setText("Tlable16");

        TLable19.setText("Tlable21");

        TLable20.setText("Tlable19");

        TLable21.setText("Tlable20");

        TLable22.setText("Tlable19");

        TLable23.setText("Tlable20");

        TLable24.setText("Tlable21");

        TLable25.setText("Tlable19");

        TLable26.setText("Tlable20");

        TLable27.setText("Tlable21");

        TLable28.setText("Tlable19");

        TLable29.setText("Tlable20");

        TLable30.setText("Tlable21");

        TLable31.setText("Tlable19");

        TLable32.setText("Tlable20");

        TLable33.setText("Tlable21");

        TLable34.setText("Tlable19");

        TLable35.setText("Tlable20");

        TLable36.setText("Tlable21");

        TLable37.setText("Tlable19");

        TLable38.setText("Tlable20");

        TLable39.setText("Tlable21");

        TLable40.setText("Tlable19");

        TLable41.setText("Tlable20");

        TLable42.setText("Tlable21");

        TLable43.setText("Tlable19");

        TLable44.setText("Tlable20");

        TLable45.setText("Tlable21");

        TLable46.setText("Tlable19");

        TLable47.setText("Tlable20");

        TLable48.setText("Tlable21");

        TLable49.setText("Tlable19");

        TLable50.setText("Tlable20");

        TLable51.setText("Tlable21");

        TLable52.setText("Tlable19");

        TLable53.setText("Tlable20");

        TLable54.setText("Tlable21");

        jLabel10.setText("Time");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1)
                        .addGap(62, 62, 62)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(85, 85, 85)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3)
                        .addGap(64, 64, 64)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4)
                        .addGap(54, 54, 54)
                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator22, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TLable2)
                                    .addComponent(TLable1)
                                    .addComponent(TLable3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TLable5)
                                    .addComponent(TLable4)
                                    .addComponent(TLable6)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TLable8)
                                    .addComponent(TLable7)
                                    .addComponent(TLable9))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator23, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TLable10)
                                    .addComponent(TLable11)
                                    .addComponent(TLable12)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TLable14)
                                    .addComponent(TLable13)
                                    .addComponent(TLable15)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TLable17)
                                    .addComponent(TLable18)
                                    .addComponent(TLable16))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator18, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                    .addComponent(jSeparator24)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TLable21)
                                    .addComponent(TLable20)
                                    .addComponent(TLable19)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TLable23)
                                    .addComponent(TLable22)
                                    .addComponent(TLable24)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TLable26)
                                    .addComponent(TLable25)
                                    .addComponent(TLable27))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator25, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TLable29)
                                    .addComponent(TLable28)
                                    .addComponent(TLable30)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TLable32)
                                    .addComponent(TLable31)
                                    .addComponent(TLable33)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TLable35)
                                    .addComponent(TLable34)
                                    .addComponent(TLable36))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator20)
                                            .addComponent(jSeparator26)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(54, 54, 54)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(TLable38)
                                                    .addComponent(TLable37)
                                                    .addComponent(TLable39)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(52, 52, 52)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(TLable41)
                                                    .addComponent(TLable40)
                                                    .addComponent(TLable42))))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TLable44)
                                    .addComponent(TLable43)
                                    .addComponent(TLable45))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator21, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator27, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TLable47)
                                    .addComponent(TLable46)
                                    .addComponent(TLable48)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TLable50)
                                    .addComponent(TLable49)
                                    .addComponent(TLable51)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TLable53)
                                    .addComponent(TLable52)
                                    .addComponent(TLable54))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator4)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel7)
                        .addGap(75, 75, 75)
                        .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel8)
                        .addGap(70, 70, 70)
                        .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(37, 37, 37)
                                    .addComponent(TLable1)
                                    .addGap(18, 18, 18)
                                    .addComponent(TLable2)
                                    .addGap(18, 18, 18)
                                    .addComponent(TLable3)
                                    .addGap(53, 53, 53)
                                    .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addComponent(TLable11)
                                    .addGap(18, 18, 18)
                                    .addComponent(TLable10)
                                    .addGap(18, 18, 18)
                                    .addComponent(TLable12)
                                    .addGap(50, 50, 50)
                                    .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(43, 43, 43)
                                    .addComponent(TLable46)
                                    .addGap(18, 18, 18)
                                    .addComponent(TLable47)
                                    .addGap(18, 18, 18)
                                    .addComponent(TLable48)
                                    .addGap(47, 47, 47)
                                    .addComponent(jSeparator21, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(34, 34, 34)
                                    .addComponent(TLable20)
                                    .addGap(18, 18, 18)
                                    .addComponent(TLable21)
                                    .addGap(18, 18, 18)
                                    .addComponent(TLable19)
                                    .addGap(56, 56, 56)
                                    .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(TLable37)
                                    .addGap(18, 18, 18)
                                    .addComponent(TLable38)
                                    .addGap(18, 18, 18)
                                    .addComponent(TLable39)
                                    .addGap(55, 55, 55)
                                    .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(TLable28)
                                .addGap(18, 18, 18)
                                .addComponent(TLable29)
                                .addGap(18, 18, 18)
                                .addComponent(TLable30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(TLable4)
                                .addGap(18, 18, 18)
                                .addComponent(TLable5)
                                .addGap(18, 18, 18)
                                .addComponent(TLable6)
                                .addGap(38, 38, 38)
                                .addComponent(jSeparator22, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(TLable13)
                                .addGap(18, 18, 18)
                                .addComponent(TLable14)
                                .addGap(18, 18, 18)
                                .addComponent(TLable15)
                                .addGap(40, 40, 40)
                                .addComponent(jSeparator23, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(TLable49)
                                .addGap(18, 18, 18)
                                .addComponent(TLable50)
                                .addGap(18, 18, 18)
                                .addComponent(TLable51)
                                .addGap(35, 35, 35)
                                .addComponent(jSeparator27, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(TLable22)
                                .addGap(18, 18, 18)
                                .addComponent(TLable23)
                                .addGap(18, 18, 18)
                                .addComponent(TLable24)
                                .addGap(37, 37, 37)
                                .addComponent(jSeparator24, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(TLable31)
                                .addGap(18, 18, 18)
                                .addComponent(TLable32)
                                .addGap(18, 18, 18)
                                .addComponent(TLable33)
                                .addGap(48, 48, 48)
                                .addComponent(jSeparator25, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(TLable40)
                                .addGap(18, 18, 18)
                                .addComponent(TLable41)
                                .addGap(18, 18, 18)
                                .addComponent(TLable42)
                                .addGap(43, 43, 43)
                                .addComponent(jSeparator26, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(TLable7)
                                .addGap(18, 18, 18)
                                .addComponent(TLable8)
                                .addGap(18, 18, 18)
                                .addComponent(TLable9))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(TLable18)
                                .addGap(18, 18, 18)
                                .addComponent(TLable17)
                                .addGap(18, 18, 18)
                                .addComponent(TLable16))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(TLable25)
                                .addGap(18, 18, 18)
                                .addComponent(TLable26)
                                .addGap(18, 18, 18)
                                .addComponent(TLable27))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(TLable34)
                                .addGap(18, 18, 18)
                                .addComponent(TLable35)
                                .addGap(18, 18, 18)
                                .addComponent(TLable36))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(TLable43)
                                .addGap(18, 18, 18)
                                .addComponent(TLable44)
                                .addGap(18, 18, 18)
                                .addComponent(TLable45))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(TLable52)
                                .addGap(18, 18, 18)
                                .addComponent(TLable53)
                                .addGap(18, 18, 18)
                                .addComponent(TLable54)))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(custom_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(custom_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(custom_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(custom_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new custom_table(cellText).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TLable1;
    private javax.swing.JLabel TLable10;
    private javax.swing.JLabel TLable11;
    private javax.swing.JLabel TLable12;
    private javax.swing.JLabel TLable13;
    private javax.swing.JLabel TLable14;
    private javax.swing.JLabel TLable15;
    private javax.swing.JLabel TLable16;
    private javax.swing.JLabel TLable17;
    private javax.swing.JLabel TLable18;
    private javax.swing.JLabel TLable19;
    private javax.swing.JLabel TLable2;
    private javax.swing.JLabel TLable20;
    private javax.swing.JLabel TLable21;
    private javax.swing.JLabel TLable22;
    private javax.swing.JLabel TLable23;
    private javax.swing.JLabel TLable24;
    private javax.swing.JLabel TLable25;
    private javax.swing.JLabel TLable26;
    private javax.swing.JLabel TLable27;
    private javax.swing.JLabel TLable28;
    private javax.swing.JLabel TLable29;
    private javax.swing.JLabel TLable3;
    private javax.swing.JLabel TLable30;
    private javax.swing.JLabel TLable31;
    private javax.swing.JLabel TLable32;
    private javax.swing.JLabel TLable33;
    private javax.swing.JLabel TLable34;
    private javax.swing.JLabel TLable35;
    private javax.swing.JLabel TLable36;
    private javax.swing.JLabel TLable37;
    private javax.swing.JLabel TLable38;
    private javax.swing.JLabel TLable39;
    private javax.swing.JLabel TLable4;
    private javax.swing.JLabel TLable40;
    private javax.swing.JLabel TLable41;
    private javax.swing.JLabel TLable42;
    private javax.swing.JLabel TLable43;
    private javax.swing.JLabel TLable44;
    private javax.swing.JLabel TLable45;
    private javax.swing.JLabel TLable46;
    private javax.swing.JLabel TLable47;
    private javax.swing.JLabel TLable48;
    private javax.swing.JLabel TLable49;
    private javax.swing.JLabel TLable5;
    private javax.swing.JLabel TLable50;
    private javax.swing.JLabel TLable51;
    private javax.swing.JLabel TLable52;
    private javax.swing.JLabel TLable53;
    private javax.swing.JLabel TLable54;
    private javax.swing.JLabel TLable6;
    private javax.swing.JLabel TLable7;
    private javax.swing.JLabel TLable8;
    private javax.swing.JLabel TLable9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
